logicalclocks/conda-chef

attributes/default.rb, recipes/default.rb, recipes/install.rb
Testing: https://github.com/hopshadoop/hops-testing/pull/22
=> Fix conda installation

attributes/default.rb, recipes/install.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-445
=> move environments out of binaries path for anaconda

recipes/default.rb, recipes/install.rb
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-468
=> [HOPSWORKS-468] Kagent restart, performance impact assessment

attributes/default.rb, recipes/install.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-627
=> [HOPSWORKS-627] [HOPSWORKS-633]

recipes/install.rb, templates/default/hops-system-environment.yml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-824
=> [HOPSWORKS-824]  Remove hard-coded mirror list in hops-system environment

attributes/default.rb, metadata.rb, recipes/install.rb, templates/default/condarc.erb
=> [HOPSWORKS-875] Add PyTorch, Torchvision and Matplotlib to python base environment

.gitignore, attributes/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1089
=> [HOPSWORKS-1089] Integrate sparkmagic with maggy

.gitignore, attributes/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1095
=> [HOPSWORKS-1095] Add back Localhost support

attributes/default.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1229
=> [HOPSWORKS-1229] Update conda to version 4.7

attributes/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1247
=> [HOPSWORKS-1247] Add attributes for installing Hopsworks EE

templates/default/hops-system-environment.yml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1261
=> [HOPSWORKS-1261] Add coloredlogs dependency

attributes/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1208
=> [HOPSWORKS-1208] Add JupyterLab version attributes

attributes/default.rb, libraries/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1331
=> [HOPSWORKS-1331] Consistent flag for system upgrades

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1355
=> [undo-HOPSWORKS] Undo HOPSWORKS-1355

attributes/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1418
=> [HOPSWORKS-1445] Bump Anaconda's python to version 3

attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1659
=> [HOPSWORKS-1659] Bump Anaconda installer to 2020.02 (#76)

attributes/default.rb, libraries/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1405
=> [consul] Add installation flag to customize services bind address

attributes/default.rb, metadata.rb
tests: https://github.com/logicalclocks/hops-testing-ee/pull/110
=> [HOPSWORKS-1862] Fix cyclic dependency error

attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1925
=> [HOPSWORKS-1925] upgrade conda to 2020.07

attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1925
=> [HOPSWORKS-1925] Backport 1.3 upgrade to conda.2020.07

attributes/default.rb, metadata.rb
Tests: 
https://github.com/logicalclocks/hops-testing-ee/pull/127
=> [HOPSWORKS-1902] Add support for managed docker registries

attributes/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2149
=> [HOPSWORKS-2149] Add attribute to allow generating dev ssh keys

attributes/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2149
=> [HOPSWORKS-2149] Add attribute to allow generating dev ssh keys (#104)

recipes/default.rb
Do not create hops-system env if kagent is not enabled
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2187
=> [HOPSWORKS-2187] Add conda user to hadoop only if the latter exists. 

attributes/default.rb, metadata.rb, recipes/default.rb, recipes/install.rb, templates/default/minimal-hops-system-environment.yml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2187
=> [HOPSWORKS-2187] Create a minimal hops-system conda environment

attributes/default.rb, metadata.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
=> [HOPSWORKS-2578]

attributes/default.rb, metadata.rb
https://hopsworks.atlassian.net/browse/HWORKS-175
=> [HWORKS-175] Export global attribute to not modify SELinux

attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-134
=> [CLOUD-134] fix image validation regex for cloud online backup

attributes/default.rb, metadata.rb
https://hopsworks.atlassian.net/browse/HWORKS-738
=> [HWORKS-738] Attributes to specify primary and secondary region names

attributes/default.rb, metadata.rb
https://hopsworks.atlassian.net/browse/HWORKS-946
=> [HWORKS-946] Export attribute to supply systemd units for the After directive of Hopsworks systemd units

attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-97
=> [CLOUD-97] Add support for GCR/GKE
